---
title: "Datathon"
author: "Ruiyi Wang"
date: "2020???2???14???"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(tidyr)
library(dplyr)
library(stringr)
library(qdap)
```


## import data
```{r}
part1 = read_csv("Datathon/Part 1.csv")
part2 = read_csv("Datathon/Part 2.csv")
part3 = read_csv("Datathon/Part 3.csv")
part5 = read_csv("Datathon/Part 5.csv")
part4a = read_csv("Datathon/Part 4a.csv")
part4b = read_csv("Datathon/Part 4b.csv")
```

```{r}
df = do.call("rbind", list(part1, part2, part3, part4a, part4b, part5))
View(df)
#write.csv(df,"C:\\Users\\Rena\\Desktop\\fulldata.csv", row.names = FALSE)
```

```{r}
df$RCPSZFE.id = as.numeric(df$RCPSZFE.id)
df$ESTAB = as.numeric(df$ESTAB)
df$YEAR.id = NULL
df$RCPSZFE.id = NULL
df = drop_na(df)
```

```{r}
df = separate(data = df, col = `GEO.display-label`, into = c("City", "State"), sep = ",")
df$City = gsub(".*\\(","",df$City)
df$State = gsub("\\)","",df$State)
```

```{r}
temp = spread(df, key = "RCPSZFE.display-label", value = "ESTAB")
temp[is.na(temp)] = 0
temp$`Establishments not operated for the entire year`[temp$`Establishments not operated for the entire year`>0] = 1
temp$totalSales = with(temp, `Establishments operated entire year with sales/receipts/revenue less than $100,000`*100000+`Establishments operated entire year with sales/receipts/revenue of $1,000,000 or more`*3000000+`Establishments operated entire year with sales/receipts/revenue of $100,000 to $249,999`*175000+`Establishments operated entire year with sales/receipts/revenue of $250,000 to $499,999`*375000+`Establishments operated entire year with sales/receipts/revenue of $500,000 to $999,999`*750000)
#temp = temp[, -c(9:13)]
temp$State = gsub(" ","",temp$State)
```
```{r}
write.csv(temp,"C:\\Users\\Rena\\Desktop\\cleaned.csv", row.names = FALSE)
```

```{r}
tax = read_csv("Datathon/12zpallagi.csv")
colnames(tax)[3] = 'GEO.id2'
```

```{r}
tax = tax[c('GEO.id2','AGI_STUB','N1','A00100','N00200','A00200','N01000','A01000','A00101','N18425','A18425','N18450','A18450','N18300','A18300')]
result$`$25,000 under $50,000`
result = potential[,-5]
result = aggregate(. ~ GEO.id+GEO.id2+City+State+`$1 under $25,000`+`$100,000 under $200,000`+`$75,000 under $100,000`+`$200,000 or more`+`$25,000 under $50,000`+`$50,000 under $75,000`, data=result, FUN=sum)
result$marketPotential = result$totalSales/result$totalIncome
result = merge(result, tax, by='GEO.id2')
write.csv(result,"C:\\Users\\Rena\\Desktop\\withtax.csv", row.names = FALSE)
```

```{r}
income = read_csv("Datathon/merged7.csv", col_names = FALSE)
View(income)
colnames(income) = c('GEO.id2','incomeRange','realEstateTax','population')
income$realEstateTax = as.numeric(income$realEstateTax)
income$population = as.numeric(income$population)
income = drop_na(income)
income = income[,-3]
```
```{r}
income = spread(income, key = "incomeRange", value = "population")
income$potential = with(income, income$`$1 under $25,000`*12500+income$`$100,000 under $200,000`*1500000+income$`$200,000 or more`*250000+income$`$25,000 under $50,000`*37500+income$`$50,000 under $75,000`*62500+income$`$75,000 under $100,000`*87500)
colnames(income)[8] = 'totalIncome'
```

```{r}
potential = merge(temp, income, by='GEO.id2')
potential = potential[potential$totalSales != 0,]
potential = potential[potential$totalIncome !=0,]
potential = drop_na(potential)
potential$marketPotential = with(potential, potential$totalSales/potential$totalIncome)
potential$marketPotential = log(100*potential$marketPotential)
percent = summary(potential$marketPotential)
potential$NAICS.id = NULL
potential = unique(potential)
recommend = potential[potential$marketPotential >= percent[[2]] & potential$marketPotential <= percent[[5]],]
write.csv(potential,"C:\\Users\\Rena\\Desktop\\full.csv", row.names = FALSE)
write.csv(recommend,"C:\\Users\\Rena\\Desktop\\result.csv", row.names = FALSE)
```

```{r}
unique(middle$State)
```
```{r}
sort(table(middle$State),decreasing=T)
```


```{r}
middle = recommend[,1:4]
middle = unique(middle)
middle = middle[,-2]
write.csv(middle, "C:\\Users\\Rena\\Desktop\\mid50list.csv",row.names = FALSE)
```


```{r}
barplot(prop.table(table(potential$`NAICS.display-label`)))
print(sort(table(potential$`NAICS.display-label`),decreasing=T)[1:10])
print(sort(table(recommend$`NAICS.display-label`),decreasing=T)[1:10])
```
```{r}

#with(potential, barplot(rev(sort(table(`NAICS.display-label`))[1:10])))
```

```{r}
plot( sort(table(recommend$`NAICS.display-label`), decreasing=TRUE)[1:10] ), type="h")
```

