---
title: "Datathon"
author: "Ruiyi Wang"
date: "2020???2???14???"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(tidyr)
library(dplyr)
library(stringr)
library(qdap)
```


## import data
```{r}
part1 = read_csv("Datathon/Part 1.csv")
part2 = read_csv("Datathon/Part 2.csv")
part3 = read_csv("Datathon/Part 3.csv")
part5 = read_csv("Datathon/Part 5.csv")
part4a = read_csv("Datathon/Part 4a.csv")
part4b = read_csv("Datathon/Part 4b.csv")
```

```{r}
df = do.call("rbind", list(part1, part2, part3, part4a, part4b, part5))
View(df)
write.csv(df,"C:\\Users\\Rena\\Desktop\\fulldata.csv", row.names = FALSE)
```

```{r}
#df$GEO.id2 = as.numeric(df$GEO.id2)
df$RCPSZFE.id = as.numeric(df$RCPSZFE.id)
df$ESTAB = as.numeric(df$ESTAB)
df$YEAR.id = NULL
```
```{r}
df = drop_na(df)
#df = filter(df, RCPSZFE.id != "1" & RCPSZFE.id != "2")
```

```{r}
#str_split_fixed(df$`GEO.display-label`, ",", 2)
df = separate(data = df, col = `GEO.display-label`, into = c("City", "State"), sep = ",")
#gsub("^.* +- +([A-Za-z ]+) \\(.*$", "\\1", df$`GEO.display-label`)
#temp = gsub("[\\(\\)]", "", regmatches(df$`GEO.display-label`, gregexpr("\\(.*?\\)", df$`GEO.display-label`))[[1]])
```

```{r}
df$City = gsub(".*\\(","",df$City)
df$State = gsub("\\)","",df$State)
```

```{r}
df$RCPSZFE.id = NULL
temp = spread(df, key = "RCPSZFE.display-label", value = "ESTAB")
temp[is.na(temp)] = 0
temp$`Establishments not operated for the entire year`[temp$`Establishments not operated for the entire year`>0] = 1
temp$Score = with(temp, `Establishments operated entire year with sales/receipts/revenue less than $100,000`*1+`Establishments operated entire year with sales/receipts/revenue of $1,000,000 or more`*10+`Establishments operated entire year with sales/receipts/revenue of $100,000 to $249,999`*1.75+`Establishments operated entire year with sales/receipts/revenue of $250,000 to $499,999`*3.75+`Establishments operated entire year with sales/receipts/revenue of $500,000 to $999,999`*7.5)
temp = temp[, -c(9:13)]
```
```{r}
temp$NAICS.id = NULL
temp = unique(temp)
write.csv(temp,"C:\\Users\\Rena\\Desktop\\cleaned.csv", row.names = FALSE)
```

```{r}
tax = read_csv("Datathon/12zpallagi.csv")
colnames(tax)[3] = 'GEO.id2'
```

```{r}
tax = tax[c('GEO.id2','AGI_STUB','N1','A00100','N00200','A00200','N01000','A01000','A00101','N18425','A18425','N18450','A18450','N18300','A18300')]
result = temp[,-c(5,6)]
result = aggregate(. ~ GEO.id+GEO.id2+City+State, data=result, FUN=sum)
result = merge(result, tax, by='GEO.id2')
write.csv(result,"C:\\Users\\Rena\\Desktop\\withtax.csv", row.names = FALSE)
```

```{r}
ecn = read_csv("Datathon/ECN_2012_US_44A1_with_ann.csv")
ecn = ecn[,-c(1,2)]
ecn = ecn[-1,]
ecn = ecn[,-c(4,5)]
ecn$`GEO.display-label` = mgsub(state.name, state.abb, ecn$`GEO.display-label`)
temp$State = gsub(" ","",temp$State)
data = temp[,-3]
colnames(ecn)[1] = 'State'
data = data[,-5]
data = data[,-c(1,2)]
data = aggregate(. ~ NAICS.id+State, data = data, FUN = sum)
output = merge(data, ecn, by = c('State','NAICS.id'))
write.csv(output,"C:\\Users\\Rena\\Desktop\\typeAndstate.csv", row.names = FALSE)
```

